var data = 
{
    "type": "FeatureCollection",
    "name": "sections-knp",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
    { "type": "Feature", "properties": { "Name": "Pafuri", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -22.582571, "name_sections_Long": 31.183535, "name_sections_Poaching": 0.83 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Vlakteplaas", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -22.87134, "name_sections_Long": 31.23099, "name_sections_Poaching": 2.13 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Shangoni", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.24, "name_sections_Long": 30.975, "name_sections_Poaching": 2.1 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Woodlands", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.043995, "name_sections_Long": 31.2326, "name_sections_Poaching": 2.17 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Shingwedzi", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.116667, "name_sections_Long": 31.4333, "name_sections_Poaching": 1.23 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Mooiplaas", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.5394, "name_sections_Long": 31.4464, "name_sections_Poaching": 1.1 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Mahlangeni", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.64804, "name_sections_Long": 31.14796, "name_sections_Poaching": 1.97 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Phalaborwa", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.9458, "name_sections_Long": 31.1658, "name_sections_Poaching": 2.5 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Letaba", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.851, "name_sections_Long": 31.57666, "name_sections_Poaching": 1.2 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Olifants", "Designatio": "National Park", "IUCN": "II", "Country": "South AfricaSouth Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.005, "name_sections_Long": 31.74, "name_sections_Poaching": 2.6 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Houtboschrand", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.098894, "name_sections_Long": 31.547779, "name_sections_Poaching": 10.33 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Nwanetsi", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.458, "name_sections_Long": 31.9761, "name_sections_Poaching": 15.7 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Kingfisherspruit", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.515097, "name_sections_Long": 31.335445, "name_sections_Poaching": 9.4 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Satara", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.3977, "name_sections_Long": 31.777, "name_sections_Poaching": 4.13 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Tshokwane", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.76306, "name_sections_Long": 31.78222, "name_sections_Poaching": 6.33 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Skukuza", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.995277, "name_sections_Long": 31.5927777, "name_sections_Poaching": 6.03 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Pretoriuskop", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.172, "name_sections_Long": 31.269, "name_sections_Poaching": 9.53 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Stolsnek", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.341654, "name_sections_Long": 31.381684, "name_sections_Poaching": 5.23 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Malelane", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.472, "name_sections_Long": 31.5088, "name_sections_Poaching": 1.8 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Crocodile Bridge", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.3583, "name_sections_Long": 31.892, "name_sections_Poaching": 5.93 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Lower Sabie", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.1211, "name_sections_Long": 31.9172, "name_sections_Poaching": 7.43 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
    { "type": "Feature", "properties": { "Name": "Punda Maria", "Designatio": "National Park", "IUCN": "II", "Country": "South Africa", "Size_ha": null, "name_gis": "Kruger National Park", "TFCA": "Great Limpopo Transfrontier Park", "Area_km2": null, "GlobalID": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -22.69211, "name_sections_Long": 31.01678, "name_sections_Poaching": 0.3 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } }
    ]
    }