var sections = 
{
    "type": "FeatureCollection",
    "name": "knp-shp-sections",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
{ "type": "Feature", "properties": { "Name": "Pafuri", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -22.582571, "name_sections_Long": 31.183535, "name_sections_Poaching": 0.83 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Vlakteplaas", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -22.87134, "name_sections_Long": 31.23099, "name_sections_Poaching": 2.13 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Shangoni", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.24, "name_sections_Long": 30.975, "name_sections_Poaching": 2.1 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Woodlands", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.043995, "name_sections_Long": 31.2326, "name_sections_Poaching": 2.17 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Shingwedzi", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.116667, "name_sections_Long": 31.4333, "name_sections_Poaching": 1.23 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Mooiplaas", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.5394, "name_sections_Long": 31.4464, "name_sections_Poaching": 1.1 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Mahlangeni", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.64804, "name_sections_Long": 31.14796, "name_sections_Poaching": 1.97 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Phalaborwa", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.9458, "name_sections_Long": 31.1658, "name_sections_Poaching": 2.5 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Letaba", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -23.851, "name_sections_Long": 31.57666, "name_sections_Poaching": 1.2 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Olifants", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.005, "name_sections_Long": 31.74, "name_sections_Poaching": 2.6 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Houtboschrand", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.098894, "name_sections_Long": 31.547779, "name_sections_Poaching": 10.33 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Nwanetsi", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.458, "name_sections_Long": 31.9761, "name_sections_Poaching": 15.7 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Kingfisherspruit", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.452, "name_sections_Long": 31.502, "name_sections_Poaching": 9.4 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Satara", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.3977, "name_sections_Long": 31.777, "name_sections_Poaching": 4.13 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Tshokwane", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.76306, "name_sections_Long": 31.78222, "name_sections_Poaching": 6.33 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Skukuza", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -24.995277, "name_sections_Long": 31.5927777, "name_sections_Poaching": 6.03 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Pretoriuskop", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.172, "name_sections_Long": 31.269, "name_sections_Poaching": 9.53 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Stolsnek", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.341654, "name_sections_Long": 31.381684, "name_sections_Poaching": 5.23 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Malelane", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.472, "name_sections_Long": 31.5088, "name_sections_Poaching": 1.8 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Crocodile Bridge", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.3583, "name_sections_Long": 31.892, "name_sections_Poaching": 5.93 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Lower Sabie", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -25.1211, "name_sections_Long": 31.9172, "name_sections_Poaching": 7.43 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "Name": "Punda Maria", "Size_ha": null, "Shape__Are": null, "Shape__Len": null, "name_sections_Lat": -22.69211, "name_sections_Long": 31.01678, "name_sections_Poaching": 0.3 }, "geometry": { "type": "MultiPolygon", "coordinates": [ ] } }
]
}